In [19]:
import pandas as pd
import timeSync

csvpath ="cr-sensor3-test.csv"
data = pd.read_csv(csvpath, names = ['rawTime','temp','humidity'])

In [28]:
testSeries = list(data['rawTime'])
data

     rawTime   temp  humidity
0          0  29.92     60.60
1        225  36.56     52.25
2        450  34.46     49.63
3        675  33.32     52.11
4        900  32.99     53.72
5       1125  32.85     54.99
6       1350  32.73     56.07
7       1575  32.69     57.10
8       1800  32.67     57.97
9       2025  32.64     58.83
10      2250  32.64     59.66
11      2475  32.64     60.44
12      2700  32.63     61.18
13      2925  32.66     61.92
14      3150  32.67     62.61
15      3375  32.64     63.31
16      3600  32.64     64.02
17      3825  32.67     64.68
18      4050  32.64     65.34
19      4275  32.67     65.98
20      4500  32.67     66.62
21      4725  32.67     67.22
22      4950  32.67     67.86
23      5175  32.67     68.46
24      5400  32.66     69.04
25      5625  32.63     69.63
26      5850  32.61     70.19
27      6075  32.62     70.74
28      6300  32.61     71.26
29      6525  32.58     71.82
..       ...    ...       ...
155    16875  32.25     98.84
156    17100  32.26     98.93
157    17325  32.31     99.01
158    17550  32.31     99.08
159    17775  32.34     99.16
160    18000  32.35     99.23
161    18225  32.39     99.30
162    18450  32.40     99.38
163    18675  32.42     99.48
164    18900  32.41     99.52
165    19125  32.41     99.62
166    19350  32.44     99.71
167    19575  32.44     99.78
168    19800  32.43     99.85
169    20025  32.43     99.93
170    20250  32.44    100.00
171    20475  32.42    100.09
172    20700  32.42    100.14
173    20925  32.40    100.23
174    21150  32.39    100.29
175    21375  32.39    100.38
176    21600  32.38    100.45
177    21825  32.34    100.51
178    22050  32.30    100.61
179    22275  32.29    100.64
180    22500  32.28    100.73
181    22725  32.25    100.82
182    22950  32.25    100.88
183    23175  32.20    100.94
184    23400  32.18    101.02

[185 rows x 3 columns]

In [33]:
if len(data) > 0:
    #multiply to get time in seconds
    data['rawTime'] = data['rawTime']*8

    timeSeries = data['rawTime']

    timeSync.checkResetOverflow(timeSeries)

    pd.DataFrame.to_csv(data,path_or_buf=csvpath+"-clean")

less than
edited due to overflow or reset at row 80